[plugin]
id = "constraint-compiler-plugin"
class = "io.ballerina.stdlib.data.csvdata.compiler.CsvDataCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/data.csv-compiler-plugin-@project.version@.jar"
