[plugin]
id = "constraint-compiler-plugin"
class = "compiler.io.ballerina.lib.data.csvdata.CsvDataCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/data.csv-compiler-plugin-0.1.0-SNAPSHOT.jar"
